plugins {
	id "java-library"
	id "idea"
	id "jacoco"
	id 'java-test-fixtures'
}

dependencies {
	implementation libs.aspectjrt,
			libs.powertools.logging.log4j,
			libs.powertools.metrics,
			project(":lib"),
			libs.limeade,
			libs.cri.common.lib,
			libs.aws.sdk.dynamodb.enhanced,
			libs.bundles.jackson,
			libs.apache.httpcomponents.httpcore,
			libs.apache.httpcomponents.httpclient

	testImplementation testFixtures(project(":lib"))

	testFixturesImplementation testFixtures(project(":lib")),
			libs.aspectjrt,
			libs.bundles.jackson,
			libs.apache.httpcomponents.httpcore,
			libs.apache.httpcomponents.httpclient
}
